# Generated by Django 4.2.2 on 2023-06-27 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("student", "0002_student_photo_alter_student_floor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Grade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=155, verbose_name="Название")),
                (
                    "students",
                    models.ManyToManyField(
                        related_name="student_grade", to="student.student"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_grade",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Учитель",
                    ),
                ),
            ],
        ),
    ]
