# Generated by Django 4.2.2 on 2023-06-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="school",
            name="grade",
        ),
        migrations.AddField(
            model_name="school",
            name="grades",
            field=models.CharField(default=1, max_length=155, verbose_name="Классы"),
            preserve_default=False,
        ),
    ]
