# Generated by Django 4.2.2 on 2023-06-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0002_teacher_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Номер телефона"
            ),
        ),
    ]
