# Generated by Django 4.2.2 on 2023-06-26 18:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0004_alter_teacher_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(
                default=1, max_length=10, verbose_name="Номер телефона"
            ),
            preserve_default=False,
        ),
    ]
