# Generated by Django 4.2.2 on 2023-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0005_alter_teacher_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="grade",
            field=models.CharField(max_length=50, verbose_name="Класс"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="phone_number",
            field=models.CharField(
                max_length=10, unique=True, verbose_name="Номер телефона"
            ),
        ),
    ]
