# Generated by Django 4.2.2 on 2023-06-27 14:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0006_alter_teacher_grade_alter_teacher_phone_number"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="teacher",
            managers=[],
        ),
    ]
