# Generated by Django 4.2.2 on 2023-06-27 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0007_alter_teacher_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                verbose_name="Адресс электронной почты",
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(max_length=155, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="is_staff",
            field=models.BooleanField(default=True, verbose_name="Персонал"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="is_superuser",
            field=models.BooleanField(default=False, verbose_name="Админ"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(max_length=155, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="username",
            field=models.CharField(max_length=150, verbose_name="Имя пользователя"),
        ),
    ]
