# Generated by Django 4.2.2 on 2023-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("teacher", "0008_alter_teacher_email_alter_teacher_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="email",
            field=models.EmailField(
                max_length=254, verbose_name="Адресс электронной почты"
            ),
        ),
    ]
