# Generated by Django 4.2.2 on 2023-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fio", models.CharField(max_length=155, verbose_name="ФИО")),
                (
                    "mail",
                    models.EmailField(
                        max_length=155, unique=True, verbose_name="Email"
                    ),
                ),
                ("date_birth", models.DateField(verbose_name="Дата Рождения")),
                ("grade", models.CharField(max_length=50, verbose_name="Класс")),
                ("address", models.CharField(max_length=50, verbose_name="Адрес")),
                (
                    "floor",
                    models.CharField(
                        choices=[("MALE", "MALE"), ("FEMALE", "FEMALE")],
                        max_length=6,
                        verbose_name="Пол",
                    ),
                ),
            ],
        ),
    ]
