# Generated by Django 4.2.2 on 2023-06-26 17:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="photo",
            field=models.ImageField(default=1, upload_to="", verbose_name="Фото"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="student",
            name="floor",
            field=models.CharField(
                choices=[("MALE", "Мужчина"), ("FEMALE", "Женщина")],
                max_length=6,
                verbose_name="Пол",
            ),
        ),
    ]
