# Generated by Django 4.2.2 on 2023-06-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0002_student_photo_alter_student_floor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(upload_to="media/students", verbose_name="Фото"),
        ),
    ]
