# Generated by Django 4.2.2 on 2023-06-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0003_alter_student_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/students", verbose_name="Фото"
            ),
        ),
    ]
